export const TICKETING_COPY = {
  heroEyebrow: "Coronation Night 2026",
  heroTitle: "Fair tickets, on-chain",
  heroDescription:
    "When ticketing opens, pay in USDC and receive a Base ticket with your tier and seat — scannable at the door and independently verifiable.",
  onChainTag: "on-chain",
  testUsdcLabel: "Your test USDC",
  testUsdcButton: "Get test USDC",
  tierHeading: "1. Pick your tier",
  bookingHeading: "2. Book your seat",
  bookingDescription: "Connect your Base wallet to continue when ticketing opens.",
  connectToBuy: "Connect your Base wallet to continue.",
  ticketsHeading: "Your tickets",
  demoHeading: "Demo",
  demoDescription: "Preview the",
  voucherDemoLink: "voucher print layout",
  verifyDemoLink: "check-in scanner",
  successTitle: "Ticket purchased!",
  successDescription: "Your voucher is ready — print it or save as PDF for the venue.",
};
